site_name: mkdocs_ptype
repo_name: https://github.com/verituslabs/mkdocs_ptype
site_url: https://verituslabs.github.io/mkdocs_ptype
repo_name: mkdocs_ptype
edit_uri: ""

docs_dir: doc
site_dir: site

# give a title for each page
nav:
  - 'Home': 'index.md'

